version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=healthy-app
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env